export const CATEGORY_FETCH_REQUEST = "CATEGORY_FETCH_REQUEST"
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS"
export const CATEGORY_FETCH_FAIL = "CATEGORY_FETCH_FAIL"

export const CATEGORY_FILTER_FETCH_REQUEST = "CATEGORY_FILTER_FETCH_REQUEST"
export const CATEGORY_FILTER_FETCH_SUCCESS = "CATEGORY_FILTER_FETCH_SUCCESS"
export const CATEGORY_FILTER_FETCH_FAIL = "CATEGORY_FILTER_FETCH_FAIL"