export const PRODUCT_FETCH_REQUEST = "PRODUCT_FETCH_REQUEST"
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS"
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL"

export const PRODUCT_ARRIVAL_FETCH_REQUEST = "PRODUCT_ARRIVAL_FETCH_REQUEST"
export const PRODUCT_ARRIVAL_FETCH_SUCCESS = "PRODUCT_ARRIVAL_FETCH_SUCCESS"
export const PRODUCT_ARRIVAL_FETCH_FAIL = "PRODUCT_ARRIVAL_FETCH_SUCCESS"

export const PRODUCT_READ_REQUEST = "PRODUCT_READ_REQUEST"
export const PRODUCT_READ_SUCCESS = "PRODUCT_READ_SUCCESS"
export const PRODUCT_READ_FAIL = "PRODUCT_READ_FAIL"